name: nextbus
description: A library for interacting with the Nextbus API.
version: 0.0.1
author: Harry Stern <hcs@meow.sh>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3
  xml: ^2.6.0

dev_dependencies:
  test: ^0.12.0
